[2022-08-22 22:00:05,722] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_deskmanager.popula_DeskManagerAF scheduled__2022-08-21T22:00:00+00:00 [queued]>
[2022-08-22 22:00:05,770] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_deskmanager.popula_DeskManagerAF scheduled__2022-08-21T22:00:00+00:00 [queued]>
[2022-08-22 22:00:05,770] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 22:00:05,770] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-22 22:00:05,771] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 22:00:05,888] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): popula_DeskManagerAF> on 2022-08-21 22:00:00+00:00
[2022-08-22 22:00:05,948] {standard_task_runner.py:52} INFO - Started process 103694 to run task
[2022-08-22 22:00:05,974] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'carga_deskmanager', 'popula_DeskManagerAF', 'scheduled__2022-08-21T22:00:00+00:00', '--job-id', '1973', '--raw', '--subdir', 'DAGS_FOLDER/etl_deskmanager.py', '--cfg-path', '/tmp/tmpbazg_n3b', '--error-file', '/tmp/tmp8lb7n6xn']
[2022-08-22 22:00:06,051] {standard_task_runner.py:80} INFO - Job 1973: Subtask popula_DeskManagerAF
[2022-08-22 22:00:06,817] {task_command.py:371} INFO - Running <TaskInstance: carga_deskmanager.popula_DeskManagerAF scheduled__2022-08-21T22:00:00+00:00 [running]> on host 1e1070d9e5ae
[2022-08-22 22:00:07,726] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clecio.antao@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=carga_deskmanager
AIRFLOW_CTX_TASK_ID=popula_DeskManagerAF
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T22:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-21T22:00:00+00:00
[2022-08-22 22:00:07,839] {logging_mixin.py:115} INFO - sucesso
[2022-08-22 22:00:09,012] {logging_mixin.py:115} INFO - Token:  dGVjYmFu#d8d76623d83283c2bc7df406a7dc06c6921aa6f7
[2022-08-22 22:00:09,014] {logging_mixin.py:115} INFO - Relatorio:  868
[2022-08-22 22:00:09,014] {logging_mixin.py:115} INFO - Tabela:  DeskManagerAF
[2022-08-22 22:00:18,490] {logging_mixin.py:115} INFO - Paginas:  5000
[2022-08-22 22:00:18,579] {logging_mixin.py:115} INFO - Contador:  1
[2022-08-22 22:00:18,579] {logging_mixin.py:115} INFO - Linhas:  0
[2022-08-22 22:00:24,460] {logging_mixin.py:115} INFO - 30 30
[2022-08-22 22:01:21,360] {logging_mixin.py:115} INFO - Paginas:  5000
[2022-08-22 22:01:21,361] {logging_mixin.py:115} INFO - Contador:  2
[2022-08-22 22:01:21,361] {logging_mixin.py:115} INFO - Linhas:  5000
[2022-08-22 22:01:22,017] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/callables.py", line 101, in carrega_dados
    resp_data = json.loads(resp.text)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-08-22 22:01:22,049] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=carga_deskmanager, task_id=popula_DeskManagerAF, execution_date=20220821T220000, start_date=20220822T220005, end_date=20220822T220122
[2022-08-22 22:01:22,114] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-08-22 22:01:22,139] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2022-08-22 22:01:22,140] {email.py:228} INFO - Email alerting: attempt 1
[2022-08-22 22:01:22,162] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2022-08-22 22:01:22,167] {email.py:228} INFO - Email alerting: attempt 1
[2022-08-22 22:01:22,168] {taskinstance.py:1964} ERROR - Failed to send email to: ['clecio.antao@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1471, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1618, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/callables.py", line 101, in carrega_dados
    resp_data = json.loads(resp.text)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2346, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1962, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2348, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-08-22 22:01:22,237] {standard_task_runner.py:97} ERROR - Failed to execute job 1973 for task popula_DeskManagerAF (Expecting value: line 1 column 1 (char 0); 103694)
[2022-08-22 22:01:22,322] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-22 22:01:22,551] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
