[2022-08-18 14:04:15,677] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: elastic_desk.popula_elastic_finalizados manual__2022-08-18T14:04:12.916264+00:00 [queued]>
[2022-08-18 14:04:15,695] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: elastic_desk.popula_elastic_finalizados manual__2022-08-18T14:04:12.916264+00:00 [queued]>
[2022-08-18 14:04:15,695] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 14:04:15,695] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-18 14:04:15,695] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 14:04:15,735] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): popula_elastic_finalizados> on 2022-08-18 14:04:12.916264+00:00
[2022-08-18 14:04:15,752] {standard_task_runner.py:52} INFO - Started process 4391 to run task
[2022-08-18 14:04:15,759] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'elastic_desk', 'popula_elastic_finalizados', 'manual__2022-08-18T14:04:12.916264+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_elastic_desk.py', '--cfg-path', '/tmp/tmpmsvu9ms0', '--error-file', '/tmp/tmpx5q8er14']
[2022-08-18 14:04:15,760] {standard_task_runner.py:80} INFO - Job 6: Subtask popula_elastic_finalizados
[2022-08-18 14:04:15,885] {task_command.py:371} INFO - Running <TaskInstance: elastic_desk.popula_elastic_finalizados manual__2022-08-18T14:04:12.916264+00:00 [running]> on host 616fda3d6fc3
[2022-08-18 14:04:16,048] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clecio.antao@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_desk
AIRFLOW_CTX_TASK_ID=popula_elastic_finalizados
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T14:04:12.916264+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T14:04:12.916264+00:00
[2022-08-18 14:04:16,049] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/callables.py", line 301, in popula_elastic_finalizados
    ep = es_pandas(es_host)
NameError: name 'es_pandas' is not defined
[2022-08-18 14:04:16,069] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=elastic_desk, task_id=popula_elastic_finalizados, execution_date=20220818T140412, start_date=20220818T140415, end_date=20220818T140416
[2022-08-18 14:04:16,102] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-08-18 14:04:16,103] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2022-08-18 14:04:16,103] {email.py:228} INFO - Email alerting: attempt 1
[2022-08-18 14:04:16,119] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2022-08-18 14:04:16,119] {email.py:228} INFO - Email alerting: attempt 1
[2022-08-18 14:04:16,119] {taskinstance.py:1964} ERROR - Failed to send email to: ['clecio.antao@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1471, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1618, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/callables.py", line 301, in popula_elastic_finalizados
    ep = es_pandas(es_host)
NameError: name 'es_pandas' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2346, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1962, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2348, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-08-18 14:04:16,146] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task popula_elastic_finalizados (name 'es_pandas' is not defined; 4391)
[2022-08-18 14:04:16,203] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-18 14:04:16,289] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
