[2022-08-18 07:47:28,818] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_deskmanager.popula_DeskManagerAF manual__2022-08-18T07:47:26.174370+00:00 [queued]>
[2022-08-18 07:47:28,879] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_deskmanager.popula_DeskManagerAF manual__2022-08-18T07:47:26.174370+00:00 [queued]>
[2022-08-18 07:47:28,879] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 07:47:28,879] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-18 07:47:28,879] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 07:47:28,966] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): popula_DeskManagerAF> on 2022-08-18 07:47:26.174370+00:00
[2022-08-18 07:47:28,994] {standard_task_runner.py:52} INFO - Started process 765 to run task
[2022-08-18 07:47:29,019] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'carga_deskmanager', 'popula_DeskManagerAF', 'manual__2022-08-18T07:47:26.174370+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_deskmanager.py', '--cfg-path', '/tmp/tmpgnqjcjjf', '--error-file', '/tmp/tmpm0mhamai']
[2022-08-18 07:47:29,053] {standard_task_runner.py:80} INFO - Job 4: Subtask popula_DeskManagerAF
[2022-08-18 07:47:29,276] {task_command.py:371} INFO - Running <TaskInstance: carga_deskmanager.popula_DeskManagerAF manual__2022-08-18T07:47:26.174370+00:00 [running]> on host b471eb8f525c
[2022-08-18 07:47:29,397] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clecio.antao@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=carga_deskmanager
AIRFLOW_CTX_TASK_ID=popula_DeskManagerAF
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T07:47:26.174370+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T07:47:26.174370+00:00
[2022-08-18 07:47:29,398] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/callables.py", line 34, in carrega_dados
    engineorigem = sa.engine.URL.create(
NameError: name 'sa' is not defined
[2022-08-18 07:47:29,412] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=carga_deskmanager, task_id=popula_DeskManagerAF, execution_date=20220818T074726, start_date=20220818T074728, end_date=20220818T074729
[2022-08-18 07:47:29,438] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-08-18 07:47:29,438] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2022-08-18 07:47:29,438] {email.py:228} INFO - Email alerting: attempt 1
[2022-08-18 07:47:29,457] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2022-08-18 07:47:29,457] {email.py:228} INFO - Email alerting: attempt 1
[2022-08-18 07:47:29,458] {taskinstance.py:1964} ERROR - Failed to send email to: ['clecio.antao@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1471, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1618, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/callables.py", line 34, in carrega_dados
    engineorigem = sa.engine.URL.create(
NameError: name 'sa' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2346, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1962, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2348, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-08-18 07:47:29,476] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task popula_DeskManagerAF (name 'sa' is not defined; 765)
[2022-08-18 07:47:29,482] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-18 07:47:29,534] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
